#!/bin/bash

TIMEOUT=3

get() {
  VAL=`pamixer --get-volume`
  HUM=`pamixer --get-volume-human`
  ICO='ﱝ'
  if ((VAL >= 30)); then
    ICO=''
  elif ((VAL >= 10)); then
    ICO=''
  elif ((VAL >= 0)); then
    ICO=''
  fi
  echo "{\"value\": $VAL, \"human\": \"$HUM\", \"icon\": \"$ICO\", \"time\": $(date +%s)}"
}

close() {
  sleep $TIMEOUT
  cur=$(tail -1 /tmp/eww/volume)
  if (($1 >= $(echo $cur | jq '.time'))); then
    eww close volume
  fi
}

down() {
  eww close brightness
  eww open volume
  pamixer -d 3
  cur=$(get)
  echo $cur >> /tmp/eww/volume
  canberra-gtk-play -i audio-volume-change -d "changevolume"
  $HOME/.config/eww/scripts/audio refresh
  close $(echo $cur | jq '.time')
}

up() {
  eww close brightness
  eww open volume
  pamixer -i 3
  cur=$(get)
  echo $cur >> /tmp/eww/volume
  canberra-gtk-play -i audio-volume-change -d "changevolume"
  $HOME/.config/eww/scripts/audio refresh
  close $(echo $cur | jq '.time')
}

mute() {
  eww close brightness
  eww open volume
  DEFAULT_SINK=$(pactl info | grep "Default Sink" | cut -d " " -f3)
  pactl set-sink-mute @DEFAULT_SINK@ toggle
  cur=$(get)
  echo $cur >> /tmp/eww/volume
  canberra-gtk-play -i audio-volume-change -d "changevolume"
  $HOME/.config/eww/scripts/audio refresh
  close $(echo $cur | jq '.time')
}

case "$1" in
  get) get;;
  up) up;;
  down) down;;
  mute) mute;;
  control) pavucontrol &;;
esac
