#!/bin/bash

declare -A sinks
sinks['pro_x']='alsa_output.usb-Logitech_PRO_X_Wireless_Gaming_Headset-00.analog-stereo'
sinks['hdmi']='alsa_output.pci-0000_01_00.1.hdmi-stereo'
sinks['integrated']='alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink'
sinks['integrated']='alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink'

jqu() {
  jq --unbuffered --compact-output
}

set() {
  sink=${sinks[$1]}
  pactl set-default-sink $sink
}

get_active_state() {
  default_sink=$(pactl get-default-sink)
  exists=$(pactl list short sinks | awk '{print $2}' | grep $sink)
  if [ -z $exists ]; then
    echo '{"alt": ""}' | jqu
  elif [ "$default_sink" == "$sink" ]; then
    echo '{"alt": "true", "class": "active"}' | jqu
  else
    echo '{"alt": "false", "class": "inactive"}' | jqu
  fi
}

active() {
  sink=${sinks[$1]}
  get_active_state
  pactl subscribe | grep --line-buffered 'sink' | while read -r line; do
    get_active_state
  done
}

case $1 in
  active)
    active $2
    ;;
  set)
    set $2
    ;;
  *)
    echo "Usage: $0 {active} [sink]"
    exit 1
    ;;
esac

